Recyle-Project.Web/Models/recyleObjects.cs
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Recyle_Project.Web.Models
{
    public class recyleObjects
    {
        [Key]
        public int ObjectID { get; set; }
        public string ReName { get; set; }
        public int ReValue { get; set; }
        public string ImagePath { get; set; }
        public string Reİnfo { get; set; }
        public string quotes { get; set; }
        [ForeignKey("Recyletype")]
        public int TypeID { get; set; }
        public Recyletype Recyletype { get; set; }
    }
}

Recyle-Project.Web/Controllers/RecyleController.cs
using BussinessLayer.Concrete;
using DataAccesLayer.Concrete;
using DataAccesLayer.EntityFramework;
using EntityLayer.Concrete;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis.RulesetToEditorconfig;
using Recyle_Project.Web.Models;

namespace Recyle_Project.Web.Controllers
{
    
    public class RecyleController : Controller
    {
        private Context _context;
        RecyleObjectManager om = new RecyleObjectManager(new EfRecyleObjectRepository());
        UserManager um=new UserManager(new EfUserRepository());
        
        public RecyleController(Context context)
        {
            this._context = context;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Recyle(User user)
        {
            TempData["id"] = user.UserID;
            var reobjects = om.GetAllPoints();
            return View(reobjects);
        }
        [HttpGet]
        public IActionResult RecyleObjects(int id) 
        {
            TempData["Reobjectid"] = id;
            var ids = _context.recyleObjects.Find(id).TypeID;
            var reobject = _context.recyleObjects.Find(id);
            reobject.Recyletype = _context.recyletypes.Find(ids);
            return View(reobject);
        }
        [HttpPost]
        public IActionResult RecyleObjects(RecyleObjects updateReobject, int ReobjectId)
        {
            updateReobject.ObjectID = ReobjectId;
            return View(updateReobject);
        }
        [HttpGet]
        public IActionResult Wallet(int id)
        {
            var user=um.GetById(id);
            var reobjectinfo = om.GetById(Convert.ToInt32(TempData["ReObjectid"]));
            user.ReValueWallet += reobjectinfo.ReValue;
            um.UserUpdate(user);
            return View(user);
        }
        
    }
}

Recyle-Project.Web/Controllers/WalletController.cs
using BussinessLayer.Concrete;
using DataAccesLayer.Concrete;
using DataAccesLayer.EntityFramework;
using EntityLayer.Concrete;
using Microsoft.AspNetCore.Mvc;

namespace Recyle_Project.Web.Controllers
{
    public class WalletController : Controller
    {
        public readonly Context _context;

        public WalletController(Context context)
        {
            _context = context;
        }

        UserManager um = new UserManager(new EfUserRepository());
        [HttpGet]
        public IActionResult Index(int id)
        {
            var users = um.GetById(id);
            return View(users);
        }
        [HttpPost]
        public IActionResult Index(User user,int id)
        {
            var users = um.GetById(id);
            var userx = _context.users.FirstOrDefault(x => x.walletAddress == user.SendAddress);
            //var userss = um.GetByAdress(users.SendAddress);
            userx.ReValueWallet += user.SendValue;
            users.ReValueWallet -= user.SendValue;
            um.UserUpdate(users);
            um.UserUpdate(userx);
            return RedirectToAction("Index");
        }
    }
}

Recyle-Project.Web/Views/Recyle/Index.cshtml
@using EntityLayer.Concrete;

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_LayoutRecyle.cshtml";
}


@model List<RecyleObjects>

}


<section id="hero" class="hero d-flex flex-column justify-content-center align-items-center" data-aos="fade" data-aos-delay="1500">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-6 text-center">
                <h2><span>Re'Cycle </span> Dönüşüme atmak istediğiniz nesneyi seçiniz</h2>

            </div>
        </div>
    </div>
</section><!-- End Hero Section -->
<main id="main" data-aos="fade" data-aos-delay="1500">
    <!-- ======= Gallery Section ======= -->
    <section id="gallery" class="gallery">
        <div class="container-fluid">
            <div class="row gy-4 justify-content-center">
                @foreach (var item in Model)
                {
                        <div class="col-xl-3 col-lg-4 col-md-6">
                            <div class="gallery-item h-100">
                                <img src="@item.ImagePath" class="img-fluid" alt="">
                                <div class="gallery-links d-flex align-items-center justify-content-center">
                                <h2 style="color:pink"><i><a asp-controller="Recyle" asp-action="RecyleObjects" asp-route-id="@item.ObjectID">@item.ReName</a></i> </h2>
                                </div>
                            </div>
                        </div>
                }
            </div>
        </div>
    </section>
</main>

Recyle-Project.Web/Views/Recyle/Recyle.cshtml
@{
    ViewData["Title"] = "Index";
}
@model List<recyleObjects>

}


<section id="hero" class="hero d-flex flex-column justify-content-center align-items-center" data-aos="fade" data-aos-delay="1500">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-6 text-center">
                <h2><span>Re'Cycle </span> Dönüşüme atmak istediğiniz nesneyi seçiniz</h2>

            </div>
        </div>
    </div>
</section><!-- End Hero Section -->
<main id="main" data-aos="fade" data-aos-delay="1500">
    <!-- ======= Gallery Section ======= -->
    <section id="gallery" class="gallery">
        <div class="container-fluid">
            <div class="row gy-4 justify-content-center">
                @foreach (var item in Model)
                {
                    <div class="col-xl-3 col-lg-4 col-md-6">
                        <div class="gallery-item h-100">
                            <img src="@item.ImagePath" class="img-fluid" alt="">
                            <div class="gallery-links d-flex align-items-center justify-content-center">
                                <h2 style="color:pink"><i><a asp-controller="Recyle" asp-action="RecyleObject" asp-route-id="@item.ObjectID">@item.ReName</a></i> </h2>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </section>
</main>

Recyle-Project.Web/Views/Recyle/RecyleObject.cshtml
@{
    ViewData["Title"] = "RecyleObject";
    Layout = "~/Views/Shared/_LayoutRecyle.cshtml";
}
@model recyleObjects
<h1>RecyleObject</h1>




<body>
    <!-- ======= Header ======= -->

    <main id="main" data-aos="fade" data-aos-delay="1500">
        <div class="page-header d-flex align-items-center">
            <div class="container position-relative">
                <div class="row d-flex justify-content-center">
                    <div class="col-lg-6 text-center">
                        <h2>@Model.ReName</h2>
                    </div>
                </div>
            </div>
        </div><!-- End Page Header -->
        <!-- ======= Gallery Single Section ======= -->
        <section id="gallery-single" class="gallery-single">
            <div class="container">

                <div class="position-relative h-100">
                    <div class="slides-1 portfolio-details-slider swiper">
                        <div class="swiper-wrapper align-items-center">

                            <div class="swiper-slide">
                                <img src="ImagePath" alt="">
                            </div>
                        </div>
                        <div class="swiper-pagination"></div>
                    </div>
                    <div class="swiper-button-prev"></div>
                    <div class="swiper-button-next"></div>

                </div>

                <div class="row justify-content-between gy-4 mt-4">

                    <div class="col-lg-8">
                        <div class="portfolio-description">
                            <h2><label asp-for="@Model.ReName"></label>ReName</h2>
                            <p>
                                Reİnfo
                            </p>


                            <div class="testimonial-item">
                                <p>
                                    <i class="bi bi-quote quote-icon-left"></i>
                                    @Model.quotes
                                    <i class="bi bi-quote quote-icon-right"></i>
                                </p>
                                <div>

                                    <h4>Doğa</h4>
                                </div>
                            </div>



                        </div>
                    </div>

                    <div class="col-lg-3">
                        <div class="portfolio-info">
                            <h3>Nesne Bilgileri</h3>
                            <ul>
                                <li><strong>Geri dönüşüm Değeri</strong> <span>@Model.ReValue Carbon-Coin ( C )</span> </li>
                                <li><strong>Geri dönüşüm Değeri</strong> <span>@Model.Recyletype.Name Carbon-Coin ( C )</span> </li>
                            </ul>
                        </div>
                    </div>
                    <button type="submit" class="btn btn-success d-block">Geri Dönüştür</button>
                </div>

            </div>
        </section><!-- End Gallery Single Section -->

    </main><!-- End #main -->
</body>

Recyle-Project.Web/Views/Recyle/RecyleObjects.cshtml
@using EntityLayer.Concrete
@{
    ViewData["Title"] = "BookShow";
}
@model RecyleObjects


<!DOCTYPE html>
<html lang="en">


<body>

    <!-- ======= Header ======= -->

    <main id="main" data-aos="fade" data-aos-delay="1500">

        <!-- ======= End Page Header ======= -->
        <div class="page-header d-flex align-items-center">
            <div class="container position-relative">
                <div class="row d-flex justify-content-center">
                    <div class="col-lg-6 text-center">
                        <h2>@Model.ReName</h2>
                    </div>
                </div>
            </div>
        </div><!-- End Page Header -->
        <!-- ======= Gallery Single Section ======= -->
        <section id="gallery-single" class="gallery-single">
            <div class="container">

                <div class="position-relative h-100">
                    <div class="slides-1 portfolio-details-slider swiper">
                        <div class="swiper-wrapper align-items-center">

                            <div class="swiper-slide">
                                <img src="@Model.ImagePath" alt="">
                            </div>
                        </div>
                        <div class="swiper-pagination"></div>
                    </div>
                    <div class="swiper-button-prev"></div>
                    <div class="swiper-button-next"></div>

                </div>

                <div class="row justify-content-between gy-4 mt-4">

                    <div class="col-lg-8">
                        <div class="portfolio-description">
                            <h2>@Model.ReName</h2>
                            <p>
                                @Model.Reİnfo
                            </p>


                            <div class="testimonial-item">
                                <p>
                                    <i class="bi bi-quote quote-icon-left"></i>
                                    @Model.quotes
                                    <i class="bi bi-quote quote-icon-right"></i>
                                </p>
                                <div>

                                    <h4>Doğa</h4>
                                </div>
                            </div>



                        </div>
                    </div>

                    <div class="col-lg-3">
                        <div class="portfolio-info">
                            <h3>Bilgiler</h3>
                            <ul>
                                <li><strong>Geri Dönüşüm Tipi:</strong> <span> @Model.Recyletype.Name</span></li>
                                <li><strong>İsim:</strong> <span> @Model.ReName</span></li>
                                <li><strong>Değeri:</strong> <span> @Model.ReValue C</span></li>
                                <li><strong>Geri Dönüşüm Noktası Seçiniz</strong> <br></br><span> <select class="custom-select custom-select custom-select-lg mb-3" style="color:green" >
                                    <option >Malatya</option>
                                    <option value="1">Turgutlu</option>
                                    <option value="2">Salihli</option>
                                    <option value="3">Ahmetli</option>
                                </select></span></li>
                                
                            </ul>
                        </div>

                        <label class="btn btn-outline-success d-block"><i class=" bi bi-recycle me-2"></i><a asp-controller="Recyle" asp-action="Wallet" asp-route-id="@TempData["id"]">Geri Dönüştür Ve Cüzdan Gör @TempData["id"] </a></label>
                    </div>

                </div>

            </div>
        </section><!-- End Gallery Single Section -->

    </main><!-- End #main -->
    <!-- ======= Footer ======= -->





</body>

</html>

Recyle-Project.Web/Views/Recyle/Wallet.cshtml
@using EntityLayer.Concrete
@{
    ViewData["Title"] = "BookShow";
}
@model User


<!DOCTYPE html>
<html lang="en">


    <main id="main" data-aos="fade" data-aos-delay="1500">

        <!-- ======= End Page Header ======= -->
        <div class="page-header d-flex align-items-center">
            <div class="container position-relative">
                <div class="row d-flex justify-content-center">
                    <div class="col-lg-6 text-center">
                        <h2>@Model.userName</h2>


                    </div>
                </div>
            </div>
        </div><!-- End Page Header -->
        <!-- ======= About Section ======= -->
        <section id="about" class="about">
            <div class="container">

                <div class="row gy-4 justify-content-center">
                <div class="col-lg-4">
                    <img src="@Model.ProfileImage" class="img-fluid" alt="">
                </div>
                    <div class="col-lg-5 content">
                        <div class="row">
                        <div class="col-lg-6">

                                <ul>
                                    <li><i class="bi bi-chevron-right"></i> <strong>Hesap SHA-256 Adresi:</strong> <span>@Model.walletAddress</span></li>
                                    <li><i class="bi bi-chevron-right"></i> <strong>Carbon (C):</strong> @Model.ReValueWallet  </li>
                                @{
                                    double rcvalue = Model.ReValueWallet / 100000000.0; 
                                }
                                <li><i class="bi bi-chevron-right"></i> <strong>Recyle Coin (RC):</strong> @rcvalue  </li>

                                <li><i class="bi bi-chevron-right"></i> <strong>Telefon numarası</strong> <span>@Model.phoneNumber</span></li>

                                </ul>
                </div>
                </div>

            </div>
        </section><!-- End About Section --> 

    </main>