Recyle-Project.Web/Controllers/WalletController.cs
using BussinessLayer.Concrete;
using DataAccesLayer.Concrete;
using DataAccesLayer.EntityFramework;
using EntityLayer.Concrete;
using Microsoft.AspNetCore.Mvc;

namespace Recyle_Project.Web.Controllers
{
    public class WalletController : Controller
    {
        public readonly Context _context;

        public WalletController(Context context)
        {
            _context = context;
        }

        UserManager um = new UserManager(new EfUserRepository());
        [HttpGet]
        public IActionResult Index(int id)
        {
            var users = um.GetById(id);
            return View(users);
        }
        [HttpPost]
        public IActionResult Index(User user,int id)
        {
            var users = um.GetById(id);
            var userx = _context.users.FirstOrDefault(x => x.walletAddress == user.SendAddress);
            //var userss = um.GetByAdress(users.SendAddress);
            userx.ReValueWallet += user.SendValue;
            users.ReValueWallet -= user.SendValue;
            um.UserUpdate(users);
            um.UserUpdate(userx);
            return RedirectToAction("Index");
        }
    }
}

Recyle-Project.Web/Views/Wallet/Index.cshtml
@using EntityLayer.Concrete
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h1>Index</h1>


@model User


<!DOCTYPE html>
<html lang="en">


<main id="main" data-aos="fade" data-aos-delay="1500">

    <!-- ======= End Page Header ======= -->
    <div class="page-header d-flex align-items-center">
        <div class="container position-relative">
            <div class="row d-flex justify-content-center">
                <div class="col-lg-6 text-center">
                    <h2>@Model.userName</h2>
                </div>
            </div>
        </div>
    </div><!-- End Page Header -->
    <!-- ======= About Section ======= -->
    <section id="about" class="about">
        <div class="container">

            <div class="row gy-4 justify-content-center">
                <div class="col-lg-4">
                    <img src="@Model.ProfileImage" class="img-fluid" alt="">
                </div>
                <div class="col-lg-5 content">
                    <div class="row">
                        <div class="col-lg-6">
                            <ul>
                                <li><i class="bi bi-chevron-right"></i> <strong>Hesap SHA-256 Adresi:</strong> <span>@Model.walletAddress</span></li>
                                <li>
                                    <i class="bi bi-chevron-right"></i> <strong>Carbon Coin (CC)</strong> <span>
                                        @Model.ReValueWallet
                                <li><i class="bi bi-chevron-right"></i> <strong>Recyle Coin (RC)</strong> <span>
                                                @{double RCoin = Model.ReValueWallet / 100000000.0;}@RCoin               
                                    </span></li>

                                    </span>
                                </li>
                                <li><i class="bi bi-chevron-right"></i> <strong>Telefon numarası</strong> <span>@Model.phoneNumber</span></li>
                            </ul>
                            <form asp-controller="Wallet" asp-action="Index" asp-route-type="type1" method="post">
                                <div class="form-group mb-3">
                                <input type="hidden" asp-for="UserID"  />
                                <label>Alıcı Adresi</label>

                                <input type="text" asp-for="SendAddress" class="form-control"/>
                               
                                
                                <br />
                                <label>Gönderilecek değer</label>
                                <input type="text" asp-for="SendValue" class="form-control"/>
                                </div>
                                
                                    <button class="btn btn-success"type="submit">Gönder</button>
                                
                                
                            </form>
                        </div>
                    </div>

                </div>
    </section><!-- End About Section -->

</main>